<a href="https://colab.research.google.com/github/isaevadaryna/Machine-Learning/blob/main/%D0%86%D1%81%D0%B0%D1%94%D0%B2%D0%B0_%D0%94_%D0%9E_%2C_%D0%A4%D0%86%D0%A2%2C_3_9%2C_%D0%9B%D0%B0%D0%B1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Знайти вектор, що складається з перших п'яти натуральних чисел

In [2]:
vector = np.array([1, 2, 3, 4, 5])

vector

array([1, 2, 3, 4, 5])

2. Транспонувати вектор

In [3]:
v1 = np.matrix([1, 2, 3, 4, 5])

print(v1)
v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. напишіть функцію, яка перевертає вектор у зворотньому напрямку

In [5]:
v = np.array([1, 2, 3, 4, 5])

print(v[::-1])

[5 4 3 2 1]


In [7]:
v = np.flip(v)

print(v)

[5 4 3 2 1]


4. Обчислити середнє значення вектора

In [8]:
print(np.mean(v))

3.0


5. Знайти найбільший і найменший елемент вектора

In [9]:
print(np.max(v))
print(np.min(v))

5
1


6. Обчислити скалярний добуток двох векторів

In [10]:
v1 = np.array ([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))
print(v1*v2)

32
[ 4 10 18]


7. Напишіть фкнкцію, яка нормалізує вектор

In [11]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print (norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

8. Задайте два вектораю Визначте, чи є вони ортогональнимию

In [13]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)

9. Визначити унікальні елементи вектора

In [14]:
v = np.array([1, 2, 3, 4, 5, 3])

np.unique(v)

array([1, 2, 3, 4, 5])

10. Знайти вектори

In [15]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


11. Перевірити чи дорівнює довжина вектора 5

In [16]:
vector = np.array([1, 2, 3, 4, 5])
lenght = np.linalg.norm(vector)

np.isclose(lenght, 5)

np.False_

12. Задати матрицю, заповнену випадковими числами

In [17]:
a = np.random.randint(0, 11, (3, 3))
a

array([[0, 7, 1],
       [8, 0, 1],
       [1, 0, 4]])

13. Обчислити визначник матриці

In [18]:
np.linalg.det(a)

np.float64(-216.99999999999986)

14. Знаходження оберненої матриці

In [19]:
np.linalg.inv(a)

array([[ 0.        ,  0.12903226, -0.03225806],
       [ 0.14285714,  0.00460829, -0.03686636],
       [ 0.        , -0.03225806,  0.25806452]])

15. Розв'яжіть систему лінійних рівнянь

In [20]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


16. Множення двох матриць

In [21]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4 ])

np.dot(a, b)

array([-2, -6, 16])

In [24]:
a = np.matrix ([[1, 3, -4], [0, 2, -3]])
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]
[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


17. Транспонування матриці

In [25]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [27]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


18. Перевірка симетричності матриці

In [28]:
matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
np.allclose(matrix, matrix.T)


True

19. Обчислення сліду матриці

In [29]:
np.trace(matrix)

np.int64(6)

20. Дії з матрицями

In [30]:
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


21. Піднесення матриці до ступення

In [31]:
a = np.matrix([[1, 2], [3, 4]])

np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

22. Сортування рядків або стовпців матриці

In [32]:
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [33]:
a = np.array([[1, 4], [3, 1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [36]:
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


23. Підрахувати суму елементів кожного рядка матриці

In [37]:
row_sums = np.sum(a, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка: ")
print(row_sums)

Сума елементів кожного рядка: 
[[5]
 [4]]
