<a href="https://colab.research.google.com/github/isaevadaryna/Machine-Learning/blob/main/%D0%86%D1%81%D0%B0%D1%94%D0%B2%D0%B0_%D0%94_%D0%9E_%2C_%D0%A4%D0%86%D0%A2%2C_4_9%2C_%D0%9B%D0%B0%D0%B1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створити матрицю 3*3, заповнити її випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1,6, size=(3, 3))

matrix

array([[1, 3, 5],
       [1, 5, 3],
       [4, 5, 1]])

2. Обчислити визначених матриці

In [ ]:
det = np.linalg.det(matrix)

det

np.float64(-51.999999999999986)

3. Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(4500)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(4500)

4. Знайти суму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)

sum

np.int64(28)

5. Обчислення найбільших, найменьших елементів

In [ ]:
max_element = np.max(matrix)

print("Найбільший елемент матриці: ", max_element)

min_element = np.min(matrix)

print("Найменьший елемент матриці: ", min_element)

Найбільший елемент матриці:  5
Найменьший елемент матриці:  1


6. Знайти середнє значення елементів матриці

In [ ]:
mean = np.mean(matrix)

print("Середнє значення елементів матриці: ", mean)

Середнє значення елементів матриці:  3.111111111111111


7. Знайти матрицю, що складена з квадратних коренів

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.         1.73205081 2.23606798]
 [1.         2.23606798 1.73205081]
 [2.         2.23606798 1.        ]]


8. Обчислити суму елементиів кожного рядка.

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка: ")
print(row_sums)

Сума елементів кожного рядка: 
[[ 9]
 [ 9]
 [10]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор: ")
print(vector)

#Сортування за спаданням
sorted_vector = np.sort(vector)[::-1]
print("Ветор після сортування: ")
print(sorted_vector)

Початковий вектор: 
[4 6 3 2 2 3 0 8 4 9 9 9 0 2 6 4 2 8 9 9 7 1 5 9 5]
Ветор після сортування: 
[9 9 9 9 9 9 8 8 7 6 6 5 5 4 4 4 3 3 2 2 2 2 1 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats
#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода: ",mode)
print("Медіана: ", median)
print("Середнє: ", mean)
print("Максимальне значення: ", max_value)
print("Мінімальне значення: ", min_value)

Мода:  ModeResult(mode=np.int64(9), count=np.int64(6))
Медіана:  5.0
Середнє:  5.04
Максимальне значення:  9
Мінімальне значення:  0


11. Створити дві матриці 4*4, зопвнена числами від 1 до 10ю Обчислити суму, різницю, поелементний добуток, часткую

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1: ")
print(matrix1)

print("\nМатриця 2: ")
print(matrix2)



Матриця 1: 
[[10  8 10  8]
 [ 4  2  3  4]
 [ 6  1  2  7]
 [10  8  6  9]]

Матриця 2: 
[[7 8 2 9]
 [9 8 6 4]
 [3 7 1 2]
 [2 1 7 7]]


In [ ]:
#Обчислити суму матриць
matrix_sum = matrix1 + matrix2

#Обчислити різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислити поелементний доьуток мматриць
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матрицю: ")
print(matrix_sum)

print("\nРізниця матриць: ")
print(matrix_diff)

print("\nПоелементний добуток матриць: ")
print(matrix_division)


Сума матрицю: 
[[17 16 12 17]
 [13 10  9  8]
 [ 9  8  3  9]
 [12  9 13 16]]

Різниця матриць: 
[[ 3  0  8 -1]
 [-5 -6 -3  0]
 [ 3 -6  1  5]
 [ 8  7 -1  2]]

Поелементний добуток матриць: 
[[1.42857143 1.         5.         0.88888889]
 [0.44444444 0.25       0.5        1.        ]
 [2.         0.14285714 2.         3.5       ]
 [5.         8.         0.85714286 1.28571429]]


12. Завдати вектор-рядок, що містить дійсні числа 1.0 - 8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що міститьб числа 0.0-2.0

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape(3, 3)
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])